carro/urls.py
from django.urls import path

from .import views

app_name="carro"


urlpatterns = [

    path("agregar/<int:productos_id>/", views.agregar_producto, name="agregar"),
    path("eliminar/<int:productos_id>/", views.eliminar_producto, name="eliminar"),
    path("restar/<int:productos_id>/", views.restar_producto, name="restar"),
    path("limpiar/", views.limpiar_carro, name="limpiar"),

]

webpersonal/urls.py
from django.contrib import admin
from django.urls import path,include
from core import views as core_views
from django.conf import settings
from productos import views as productos_views
from portafolio import views as portafolio_views


from contacto import views as contacto_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',core_views.home, name="inicio"),
    path('productos/',productos_views.producto, name="productos"),
    path('portafolio/',portafolio_views.portafolio, name="portafolio"),  
    path('contacto/',include('contacto.urls')),
    path('carro/', include('carro.urls')),
    path('pedidos/',include('pedidos.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('registration.urls')),

    #path('base/',core_views.urls, name="base"),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)
    
    # custom del admin

admin.site.site_header = "vivero los ocobos"
admin.site.index_title = "panel de administrador"
admin.site.site_title = "vivero ocobos"

carro/models.py
from django.db import models

# Create your models here.

portafolio/productos/models.py
from django.db import models
from django.utils.timezone import now

class category(models.Model):
    name = models.CharField(max_length=50,verbose_name="Nombre")
    created = models.DateTimeField(auto_now=True,verbose_name="fecha de creacion")
    update = models.DateTimeField(auto_now=True,verbose_name="fecha de edicion")
    
    class meta: 
        verbose_name="categoria"
        verbose_name_plural="categorias"
        ordering=["-created"]
    def __str__(self):
        return self.name
    
class productos(models.Model):
    title=models.CharField(max_length=50,verbose_name='Nombre')
    descripcion=models.TextField(verbose_name='Descripcion')
    image=models.ImageField(verbose_name='Imagen',upload_to='projects')
    marca=models.CharField(max_length=50,verbose_name='Marca')
    categories=models.ManyToManyField(category,max_length=20, verbose_name="categoria")
    price=models.FloatField(max_length=20,verbose_name="Precio")
    created=models.DateTimeField(auto_now_add=True,verbose_name='Fecha Creacion') #añade de forma automatica
    updated=models.DateTimeField(auto_now=True,verbose_name="fecha de edicion")
    

    class Meta:
        verbose_name="Producto"
        verbose_name_plural="Productos"
        ordering=["-created"] #ordena del nuevo al antiguo

    def __str__(self):
        return self.title

productos/models.py
from django.db import models
from django.utils.timezone import now

class category(models.Model):
    name = models.CharField(max_length=50,verbose_name="Nombre")
    created = models.DateTimeField(auto_now=True,verbose_name="fecha de creacion")
    update = models.DateTimeField(auto_now=True,verbose_name="fecha de edicion")
    
    class meta: 
        verbose_name="categoria"
        verbose_name_plural="categorias"
        ordering=["-created"]
    def __str__(self):
        return self.name
    
class productos(models.Model):
    title=models.CharField(max_length=50,verbose_name='Nombre')
    descripcion=models.TextField(verbose_name='Descripcion')
    image=models.ImageField(verbose_name='Imagen',upload_to='projects')
    categories=models.ManyToManyField(category,max_length=20, verbose_name="categoria")
    price=models.FloatField(max_length=20,verbose_name="Precio")
    created=models.DateTimeField(auto_now_add=True,verbose_name='Fecha Creacion') #añade de forma automatica
    updated=models.DateTimeField(auto_now=True,verbose_name="fecha de edicion")
    

    class Meta:
        verbose_name="Producto"
        verbose_name_plural="Productos"
        ordering=["-created"] #ordena del nuevo al antiguo

    def __str__(self):
        return self.title

carro/views.py
from django.shortcuts import render

from django.shortcuts import render

from .carro import Carro

from productos.models import productos

from django.shortcuts import redirect

# Create your views here.

def agregar_producto(request, productos_id):

    carro = Carro(request)

    producto = productos.objects.get(id=productos_id)

    carro.agregar(productos=producto)

    return redirect("productos")

def eliminar_producto(request, productos_id):

    carro = Carro(request)

    producto = productos.objects.get(id=productos_id)

    carro.eliminar(productos=producto)

    return redirect("productos")

def restar_producto(request, productos_id):

    carro = Carro(request)

    producto = productos.objects.get(id=productos_id)

    carro.restar_producto(productos=producto)

    return redirect("productos")

def limpiar_carro(request, productos_id):

    carro = Carro(request)

    carro.limpiar_carro

    return redirect("productos")

# Create your views here.

portafolio/productos/views.py
from django.shortcuts import render
from core.models import links
from productos.models import category
from productos.models import productos


# Create your views here.
def producto(request):
    link=links.objects.all()
    categoria=category.objects.all()
    product=productos.objects.all()
    return render (request, "productos/productos.html",{'link':link,'categoria':categoria, 'product':product})

productos/views.py
from django.shortcuts import render
from core.models import links
from productos.models import category
from productos.models import productos


# Create your views here.
def producto(request):
    link=links.objects.all()
    categoria=category.objects.all()
    product=productos.objects.all()
    return render (request, "productos/productos.html",{'link':link,'categoria':categoria, 'product':product})

portafolio/productos/templates/carro/widget.html
{% load static %}
<table class="table table-bordered" style="color: gray;">
    <link rel="stylesheet" type="text/css" href="{% static 'css/msg.css' %}">

    <thead>
        <tr>

            <th colspan="3" class="text-center">

                Carro Compras
            
            </th>
        
        </tr>

        <tr>

            <th>Producto</th>
            <th>Cantidad</th>
            <th>Suma</th>
        
        </tr>

    <thead>

    <tbody>
        {% if request.session.carro.items %}
            {% for key, value in request.session.carro.items %}

                <tr class="text-center">

                    <td>{{value.nombre}}</td>
                    <td>{{value.cantidad}}</td>
                    <td>

                        <a href="{% url 'carro:agregar' value.productos_id %}" class="btn btn-sm btn-success"> + </a>
                        <a href="{% url 'carro:restar' value.productos_id %}" class="btn btn-sm btn-success"> - </a> <br/>

                        {{value.precio|floatformat:-1}} $-COP

                    </td>
                    
                </tr>

            {% endfor %}

        {% else %}
            <tr>
                <td colspan="3">
                    <div class="alert alert-danger text-center">
                        Sin Productos
                    </div>
                </td>
            </tr>
        {% endif %}
    </tbody>

    <tfoot>
        <tr>
            <td colspan="3">

                Total: {{importe_total_carro|floatformat:-1}} $-COP

            </td>
        </tr>
        {% if request.session.carro.items %}
        <tr>
            <td colspan="3" style="text-align: center;">
                <a href="../pedidos"  class="btn btn-success">Comprar</a>
            </td>
        </tr>
        {% endif %}
    </tfoot>
    {% if messages %}
    <ul class="messages" >
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}
</table>
<style>
   .table-bordered {
        border-radius: 8px;
    box-shadow: 0 2px 4px rgba(0, 0, 0, .1), 0 8px 16px rgba(0, 0, 0, .1);
    padding-bottom: 20px;
    }
    thead > tr{
        background-color: #3d3d3d;
        color: #fff;
    }
    .btn-sm{
        height: 25px;
        margin-bottom: 8px;
        display: flex;
        align-items: center;
        justify-content: center;
    }
    tbody,tfoot{
        color: #000;
    }
</style>